### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by InnovativeCoder** [mljs/knn#12]
at new KDTree (/Users/DBRSJ/node_modules/ml-knn/lib/index.js:36:51)
    at new KNN (/Users/DBRSJ/node_modules/ml-knn/lib/index.js:323:23)
    at train (/Users/DBRSJ/Desktop/JS_Color/Knn.js:55:11)
    at dressData (/Users/DBRSJ/Desktop/JS_Color/Knn.js:51:5)
    at Converter.csv.fromFile.on.on (/Users/DBRSJ/Desktop/JS_Color/Knn.js:22:9)
    at emitOne (events.js:121:20)
    at Converter.emit (events.js:211:7)
    at Timeout._onTimeout (/Users/DBRSJ/node_modules/csvtojson/v2/Converter.js:41:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by stropitek** [comment]
Hello

Can you show us a sample of your code?
